import { INestApplication, ValidationPipe } from '@nestjs/common';
import { Test } from '@nestjs/testing';
import * as bcrypt from 'bcrypt';
import * as request from 'supertest';
import { AppModule } from '../src/app.module';
import { PrismaService } from '../src/prisma/prisma.service';
import { resetDatabase } from './reset-db';

// When Location.allowNegativeStock lets a sale consume a SEMI_FINISHED
// ingredient past zero, that shortfall should surface as a real production
// need instead of silently sitting as a negative InventoryBalance --
// OrdersService.create() now calls ProductionOrdersService.applyShortfall()
// for exactly that case, which rolls every negative sale of the same
// ingredient within one shift into a single PLANNED, autoGenerated
// ProductionOrder (see production-orders.service.ts).
describe('Auto-generated production orders from negative-stock sales (e2e)', () => {
  let app: INestApplication;
  let prisma: PrismaService;
  let adminToken: string;

  const ADMIN_PHONE = '+966500000240';
  const PASSWORD = 'NegStockProdTest123';
  const auth = (t: string) => ({ Authorization: `Bearer ${t}` });

  beforeAll(async () => {
    const moduleRef = await Test.createTestingModule({ imports: [AppModule] }).compile();
    app = moduleRef.createNestApplication();
    app.useGlobalPipes(new ValidationPipe({ whitelist: true, forbidNonWhitelisted: true, transform: true }));
    await app.init();
    prisma = app.get(PrismaService);

    await resetDatabase(prisma);
    await prisma.userRole.deleteMany({});
    await prisma.user.deleteMany({ where: { phone: ADMIN_PHONE } });

    const passwordHash = await bcrypt.hash(PASSWORD, 10);
    await prisma.user.create({ data: { name: 'Admin', phone: ADMIN_PHONE, passwordHash } });
    const loginRes = await request(app.getHttpServer()).post('/auth/login').send({ phone: ADMIN_PHONE, password: PASSWORD });
    adminToken = loginRes.body.accessToken;
  });

  afterAll(async () => {
    await app.close();
  });

  it('selling a semi-finished ingredient past zero creates a PLANNED autoGenerated production order tied to the shift', async () => {
    const location = await prisma.location.create({ data: { name: 'فرع اختبار إنتاج تلقائي 1', type: 'BRANCH', allowNegativeStock: true } });
    const rawFlour = await prisma.ingredient.create({ data: { name: 'دقيق -- اختبار إنتاج تلقائي', unit: 'g', kind: 'RAW_MATERIAL', lowStockThreshold: 0 } });
    const dough = await prisma.ingredient.create({ data: { name: 'عجينة -- اختبار إنتاج تلقائي', unit: 'g', kind: 'SEMI_FINISHED', lowStockThreshold: 0 } });
    // dough's own recipe: 2g flour per 1g dough
    await prisma.recipeLine.create({ data: { parentIngredientId: dough.id, ingredientId: rawFlour.id, quantity: 2 } });
    const item = await prisma.menuItem.create({ data: { name: 'صنف يستهلك عجينة', category: 'رئيسي', price: 10 } });
    // 5g dough per 1 item sold
    await prisma.recipeLine.create({ data: { menuItemId: item.id, ingredientId: dough.id, quantity: 5 } });

    const shiftRes = await request(app.getHttpServer()).post('/shifts').set(auth(adminToken)).send({ locationId: location.id, openingFloat: 100 });
    const shiftId = shiftRes.body.id;

    const orderRes = await request(app.getHttpServer())
      .post('/orders')
      .set(auth(adminToken))
      .send({ locationId: location.id, shiftId, channel: 'DINE_IN', lines: [{ menuItemId: item.id, quantity: 1 }] });
    expect(orderRes.status).toBe(201);

    const listRes = await request(app.getHttpServer()).get(`/production-orders?locationId=${location.id}`).set(auth(adminToken));
    expect(listRes.status).toBe(200);
    expect(listRes.body).toHaveLength(1);
    const po = listRes.body[0];
    expect(po.status).toBe('PLANNED');
    expect(po.autoGenerated).toBe(true);
    expect(po.shiftId).toBe(shiftId);
    expect(po.outputIngredientId).toBe(dough.id);
    expect(Number(po.outputQuantity)).toBe(5);

    const detail = await request(app.getHttpServer()).get(`/production-orders/${po.id}`).set(auth(adminToken));
    expect(detail.body.inputs).toHaveLength(1);
    expect(detail.body.inputs[0].ingredientId).toBe(rawFlour.id);
    expect(Number(detail.body.inputs[0].quantity)).toBe(10); // 5g dough * 2g flour/g dough
  });

  it('a second negative sale of the same ingredient in the same shift bumps the existing order instead of creating a new one', async () => {
    const location = await prisma.location.create({ data: { name: 'فرع اختبار إنتاج تلقائي 2', type: 'BRANCH', allowNegativeStock: true } });
    const rawSugar = await prisma.ingredient.create({ data: { name: 'سكر -- اختبار تجميع', unit: 'g', kind: 'RAW_MATERIAL', lowStockThreshold: 0 } });
    const syrup = await prisma.ingredient.create({ data: { name: 'شراب -- اختبار تجميع', unit: 'g', kind: 'SEMI_FINISHED', lowStockThreshold: 0 } });
    await prisma.recipeLine.create({ data: { parentIngredientId: syrup.id, ingredientId: rawSugar.id, quantity: 1 } });
    const item = await prisma.menuItem.create({ data: { name: 'صنف يستهلك شراب', category: 'حلويات', price: 8 } });
    await prisma.recipeLine.create({ data: { menuItemId: item.id, ingredientId: syrup.id, quantity: 4 } });

    const shiftRes = await request(app.getHttpServer()).post('/shifts').set(auth(adminToken)).send({ locationId: location.id, openingFloat: 100 });
    const shiftId = shiftRes.body.id;

    await request(app.getHttpServer())
      .post('/orders')
      .set(auth(adminToken))
      .send({ locationId: location.id, shiftId, channel: 'DINE_IN', lines: [{ menuItemId: item.id, quantity: 1 }] });
    await request(app.getHttpServer())
      .post('/orders')
      .set(auth(adminToken))
      .send({ locationId: location.id, shiftId, channel: 'DINE_IN', lines: [{ menuItemId: item.id, quantity: 2 }] });

    const listRes = await request(app.getHttpServer()).get(`/production-orders?locationId=${location.id}`).set(auth(adminToken));
    expect(listRes.body).toHaveLength(1); // still one PO, not two
    const po = listRes.body[0];
    expect(Number(po.outputQuantity)).toBe(12); // 4 (first order) + 8 (second order, qty 2)

    const detail = await request(app.getHttpServer()).get(`/production-orders/${po.id}`).set(auth(adminToken));
    expect(detail.body.inputs).toHaveLength(1);
    expect(Number(detail.body.inputs[0].quantity)).toBe(12); // 1g sugar per g syrup
  });

  it('does not create a production order when the sale does not go negative', async () => {
    const location = await prisma.location.create({ data: { name: 'فرع اختبار بدون نقص', type: 'BRANCH', allowNegativeStock: true } });
    const rawWater = await prisma.ingredient.create({ data: { name: 'ماء -- اختبار بدون نقص', unit: 'ml', kind: 'RAW_MATERIAL', lowStockThreshold: 0 } });
    const base = await prisma.ingredient.create({ data: { name: 'قاعدة -- اختبار بدون نقص', unit: 'ml', kind: 'SEMI_FINISHED', lowStockThreshold: 0 } });
    await prisma.recipeLine.create({ data: { parentIngredientId: base.id, ingredientId: rawWater.id, quantity: 1 } });
    // Give `base` real stock so this sale does NOT go negative.
    await prisma.inventoryBatch.create({ data: { locationId: location.id, ingredientId: base.id, batchNumber: 'TEST-STOCK-1', quantity: 100, unitCost: 1, sourceType: 'MANUAL' } });
    await prisma.inventoryBalance.create({ data: { locationId: location.id, ingredientId: base.id, quantity: 100 } });
    const item = await prisma.menuItem.create({ data: { name: 'صنف مع مخزون كافٍ', category: 'مشروبات', price: 6 } });
    await prisma.recipeLine.create({ data: { menuItemId: item.id, ingredientId: base.id, quantity: 3 } });

    const shiftRes = await request(app.getHttpServer()).post('/shifts').set(auth(adminToken)).send({ locationId: location.id, openingFloat: 100 });
    const orderRes = await request(app.getHttpServer())
      .post('/orders')
      .set(auth(adminToken))
      .send({ locationId: location.id, shiftId: shiftRes.body.id, channel: 'DINE_IN', lines: [{ menuItemId: item.id, quantity: 1 }] });
    expect(orderRes.status).toBe(201);

    const listRes = await request(app.getHttpServer()).get(`/production-orders?locationId=${location.id}`).set(auth(adminToken));
    expect(listRes.body).toHaveLength(0);
  });

  it('does not create a production order when the negative-stock ingredient is a raw material', async () => {
    const location = await prisma.location.create({ data: { name: 'فرع اختبار خامة بالسالب', type: 'BRANCH', allowNegativeStock: true } });
    const rawIce = await prisma.ingredient.create({ data: { name: 'ثلج -- اختبار خامة', unit: 'g', kind: 'RAW_MATERIAL', lowStockThreshold: 0 } });
    const item = await prisma.menuItem.create({ data: { name: 'صنف يستهلك ثلج مباشرة', category: 'مشروبات', price: 5 } });
    await prisma.recipeLine.create({ data: { menuItemId: item.id, ingredientId: rawIce.id, quantity: 50 } });

    const shiftRes = await request(app.getHttpServer()).post('/shifts').set(auth(adminToken)).send({ locationId: location.id, openingFloat: 100 });
    const orderRes = await request(app.getHttpServer())
      .post('/orders')
      .set(auth(adminToken))
      .send({ locationId: location.id, shiftId: shiftRes.body.id, channel: 'DINE_IN', lines: [{ menuItemId: item.id, quantity: 1 }] });
    expect(orderRes.status).toBe(201);

    const listRes = await request(app.getHttpServer()).get(`/production-orders?locationId=${location.id}`).set(auth(adminToken));
    expect(listRes.body).toHaveLength(0);
  });
});
