import { INestApplication, ValidationPipe } from '@nestjs/common';
import { Test } from '@nestjs/testing';
import * as bcrypt from 'bcrypt';
import * as request from 'supertest';
import { AppModule } from '../src/app.module';
import { PrismaService } from '../src/prisma/prisma.service';
import { resetDatabase } from './reset-db';

// When a sale consumes ANY ingredient a menu item's recipe needs past
// zero, that shortfall CAN surface as a real restock/production need
// instead of silently sitting as a negative InventoryBalance --
// OrdersService.create() calls ProductionOrdersService.applyShortfall()
// for exactly that case, which rolls every negative sale of the same
// ingredient within one shift into a single PLANNED, autoGenerated
// ProductionOrder (see production-orders.service.ts) -- but only when the
// branch opted into Location.autoGenerateProductionOrders (off by
// default, since a branch that always runs on negative stock would
// otherwise get one on nearly every sale). That flag ALSO lets any
// ingredient sell past zero even when Location.allowNegativeStock is off
// -- covers every menu item, not just ones built on a SEMI_FINISHED
// component: a SEMI_FINISHED ingredient with its own registered recipe
// gets a real BOM (`inputs`) on the order, while a RAW_MATERIAL or a
// recipe-less SEMI_FINISHED item gets one with an EMPTY inputs list -- a
// plain "go restock/buy N more" alert, since there's nothing automatic to
// base a real production run on.
describe('Auto-generated production orders from negative-stock sales (e2e)', () => {
  let app: INestApplication;
  let prisma: PrismaService;
  let adminToken: string;

  const ADMIN_PHONE = '+966500000240';
  const PASSWORD = 'NegStockProdTest123';
  const auth = (t: string) => ({ Authorization: `Bearer ${t}` });

  beforeAll(async () => {
    const moduleRef = await Test.createTestingModule({ imports: [AppModule] }).compile();
    app = moduleRef.createNestApplication();
    app.useGlobalPipes(new ValidationPipe({ whitelist: true, forbidNonWhitelisted: true, transform: true }));
    await app.init();
    prisma = app.get(PrismaService);

    await resetDatabase(prisma);
    await prisma.userRole.deleteMany({});
    await prisma.user.deleteMany({ where: { phone: ADMIN_PHONE } });
    await prisma.rolePermission.deleteMany({ where: { role: { name: 'NegStockProd-Test-Shift' } } });
    await prisma.role.deleteMany({ where: { name: 'NegStockProd-Test-Shift' } });

    // adminToken opens shifts as scaffolding throughout this file, and
    // reads GET /production-orders and GET /production-orders/:id below.
    const shiftPerm = await prisma.permission.upsert({
      where: { code: 'pos.manage_shift' },
      update: {},
      create: { code: 'pos.manage_shift', label: 'فتح/إغلاق وردية' },
    });
    const productionViewPerm = await prisma.permission.upsert({
      where: { code: 'production.view' },
      update: {},
      create: { code: 'production.view', label: 'عرض أوامر الإنتاج' },
    });
    const shiftRole = await prisma.role.create({ data: { name: 'NegStockProd-Test-Shift' } });
    await prisma.rolePermission.createMany({
      data: [shiftPerm, productionViewPerm].map((p) => ({ roleId: shiftRole.id, permissionId: p.id })),
    });

    const passwordHash = await bcrypt.hash(PASSWORD, 10);
    const adminUser = await prisma.user.create({ data: { name: 'Admin', phone: ADMIN_PHONE, passwordHash } });
    await prisma.userRole.create({ data: { userId: adminUser.id, roleId: shiftRole.id } });
    const loginRes = await request(app.getHttpServer()).post('/auth/login').send({ phone: ADMIN_PHONE, password: PASSWORD });
    adminToken = loginRes.body.accessToken;
  });

  afterAll(async () => {
    await app.close();
  });

  it('selling a semi-finished ingredient past zero creates a PLANNED autoGenerated production order tied to the shift', async () => {
    const location = await prisma.location.create({ data: { name: 'فرع اختبار إنتاج تلقائي 1', type: 'BRANCH', allowNegativeStock: true, autoGenerateProductionOrders: true } });
    const rawFlour = await prisma.ingredient.create({ data: { name: 'دقيق -- اختبار إنتاج تلقائي', unit: 'g', kind: 'RAW_MATERIAL', lowStockThreshold: 0 } });
    const dough = await prisma.ingredient.create({ data: { name: 'عجينة -- اختبار إنتاج تلقائي', unit: 'g', kind: 'SEMI_FINISHED', lowStockThreshold: 0 } });
    // dough's own recipe: 2g flour per 1g dough
    await prisma.recipeLine.create({ data: { parentIngredientId: dough.id, ingredientId: rawFlour.id, quantity: 2 } });
    const item = await prisma.menuItem.create({ data: { name: 'صنف يستهلك عجينة', category: 'رئيسي', price: 10 } });
    // 5g dough per 1 item sold
    await prisma.recipeLine.create({ data: { menuItemId: item.id, ingredientId: dough.id, quantity: 5 } });

    const shiftRes = await request(app.getHttpServer()).post('/shifts').set(auth(adminToken)).send({ locationId: location.id, openingFloat: 100 });
    const shiftId = shiftRes.body.id;

    const orderRes = await request(app.getHttpServer())
      .post('/orders')
      .set(auth(adminToken))
      .send({ locationId: location.id, shiftId, channel: 'DINE_IN', lines: [{ menuItemId: item.id, quantity: 1 }] });
    expect(orderRes.status).toBe(201);

    const listRes = await request(app.getHttpServer()).get(`/production-orders?locationId=${location.id}`).set(auth(adminToken));
    expect(listRes.status).toBe(200);
    expect(listRes.body).toHaveLength(1);
    const po = listRes.body[0];
    expect(po.status).toBe('PLANNED');
    expect(po.autoGenerated).toBe(true);
    expect(po.shiftId).toBe(shiftId);
    expect(po.outputIngredientId).toBe(dough.id);
    expect(Number(po.outputQuantity)).toBe(5);

    const detail = await request(app.getHttpServer()).get(`/production-orders/${po.id}`).set(auth(adminToken));
    expect(detail.body.inputs).toHaveLength(1);
    expect(detail.body.inputs[0].ingredientId).toBe(rawFlour.id);
    expect(Number(detail.body.inputs[0].quantity)).toBe(10); // 5g dough * 2g flour/g dough
  });

  it('a second negative sale of the same ingredient in the same shift bumps the existing order instead of creating a new one', async () => {
    const location = await prisma.location.create({ data: { name: 'فرع اختبار إنتاج تلقائي 2', type: 'BRANCH', allowNegativeStock: true, autoGenerateProductionOrders: true } });
    const rawSugar = await prisma.ingredient.create({ data: { name: 'سكر -- اختبار تجميع', unit: 'g', kind: 'RAW_MATERIAL', lowStockThreshold: 0 } });
    const syrup = await prisma.ingredient.create({ data: { name: 'شراب -- اختبار تجميع', unit: 'g', kind: 'SEMI_FINISHED', lowStockThreshold: 0 } });
    await prisma.recipeLine.create({ data: { parentIngredientId: syrup.id, ingredientId: rawSugar.id, quantity: 1 } });
    const item = await prisma.menuItem.create({ data: { name: 'صنف يستهلك شراب', category: 'حلويات', price: 8 } });
    await prisma.recipeLine.create({ data: { menuItemId: item.id, ingredientId: syrup.id, quantity: 4 } });

    const shiftRes = await request(app.getHttpServer()).post('/shifts').set(auth(adminToken)).send({ locationId: location.id, openingFloat: 100 });
    const shiftId = shiftRes.body.id;

    await request(app.getHttpServer())
      .post('/orders')
      .set(auth(adminToken))
      .send({ locationId: location.id, shiftId, channel: 'DINE_IN', lines: [{ menuItemId: item.id, quantity: 1 }] });
    await request(app.getHttpServer())
      .post('/orders')
      .set(auth(adminToken))
      .send({ locationId: location.id, shiftId, channel: 'DINE_IN', lines: [{ menuItemId: item.id, quantity: 2 }] });

    const listRes = await request(app.getHttpServer()).get(`/production-orders?locationId=${location.id}`).set(auth(adminToken));
    expect(listRes.body).toHaveLength(1); // still one PO, not two
    const po = listRes.body[0];
    expect(Number(po.outputQuantity)).toBe(12); // 4 (first order) + 8 (second order, qty 2)

    const detail = await request(app.getHttpServer()).get(`/production-orders/${po.id}`).set(auth(adminToken));
    expect(detail.body.inputs).toHaveLength(1);
    expect(Number(detail.body.inputs[0].quantity)).toBe(12); // 1g sugar per g syrup
  });

  it('does not create a production order when the sale does not go negative', async () => {
    const location = await prisma.location.create({ data: { name: 'فرع اختبار بدون نقص', type: 'BRANCH', allowNegativeStock: true } });
    const rawWater = await prisma.ingredient.create({ data: { name: 'ماء -- اختبار بدون نقص', unit: 'ml', kind: 'RAW_MATERIAL', lowStockThreshold: 0 } });
    const base = await prisma.ingredient.create({ data: { name: 'قاعدة -- اختبار بدون نقص', unit: 'ml', kind: 'SEMI_FINISHED', lowStockThreshold: 0 } });
    await prisma.recipeLine.create({ data: { parentIngredientId: base.id, ingredientId: rawWater.id, quantity: 1 } });
    // Give `base` real stock so this sale does NOT go negative.
    await prisma.inventoryBatch.create({ data: { locationId: location.id, ingredientId: base.id, batchNumber: 'TEST-STOCK-1', quantity: 100, unitCost: 1, sourceType: 'MANUAL' } });
    await prisma.inventoryBalance.create({ data: { locationId: location.id, ingredientId: base.id, quantity: 100 } });
    const item = await prisma.menuItem.create({ data: { name: 'صنف مع مخزون كافٍ', category: 'مشروبات', price: 6 } });
    await prisma.recipeLine.create({ data: { menuItemId: item.id, ingredientId: base.id, quantity: 3 } });

    const shiftRes = await request(app.getHttpServer()).post('/shifts').set(auth(adminToken)).send({ locationId: location.id, openingFloat: 100 });
    const orderRes = await request(app.getHttpServer())
      .post('/orders')
      .set(auth(adminToken))
      .send({ locationId: location.id, shiftId: shiftRes.body.id, channel: 'DINE_IN', lines: [{ menuItemId: item.id, quantity: 1 }] });
    expect(orderRes.status).toBe(201);

    const listRes = await request(app.getHttpServer()).get(`/production-orders?locationId=${location.id}`).set(auth(adminToken));
    expect(listRes.body).toHaveLength(0);
  });

  it('does not create a production order when the negative-stock ingredient is a raw material', async () => {
    const location = await prisma.location.create({ data: { name: 'فرع اختبار خامة بالسالب', type: 'BRANCH', allowNegativeStock: true } });
    const rawIce = await prisma.ingredient.create({ data: { name: 'ثلج -- اختبار خامة', unit: 'g', kind: 'RAW_MATERIAL', lowStockThreshold: 0 } });
    const item = await prisma.menuItem.create({ data: { name: 'صنف يستهلك ثلج مباشرة', category: 'مشروبات', price: 5 } });
    await prisma.recipeLine.create({ data: { menuItemId: item.id, ingredientId: rawIce.id, quantity: 50 } });

    const shiftRes = await request(app.getHttpServer()).post('/shifts').set(auth(adminToken)).send({ locationId: location.id, openingFloat: 100 });
    const orderRes = await request(app.getHttpServer())
      .post('/orders')
      .set(auth(adminToken))
      .send({ locationId: location.id, shiftId: shiftRes.body.id, channel: 'DINE_IN', lines: [{ menuItemId: item.id, quantity: 1 }] });
    expect(orderRes.status).toBe(201);

    const listRes = await request(app.getHttpServer()).get(`/production-orders?locationId=${location.id}`).set(auth(adminToken));
    expect(listRes.body).toHaveLength(0);
  });

  it('does not create a production order when the branch has not opted into autoGenerateProductionOrders, even though the sale goes negative', async () => {
    // Same fixture shape as the very first test in this file (SEMI_FINISHED
    // dough sold past zero), except autoGenerateProductionOrders is left at
    // its default (false) -- Location.allowNegativeStock alone lets the
    // sale go through into deficit, but no PLANNED production order should
    // be raised for it.
    const location = await prisma.location.create({ data: { name: 'فرع اختبار إنتاج تلقائي معطّل', type: 'BRANCH', allowNegativeStock: true } });
    const rawFlour = await prisma.ingredient.create({ data: { name: 'دقيق -- اختبار إنتاج معطّل', unit: 'g', kind: 'RAW_MATERIAL', lowStockThreshold: 0 } });
    const dough = await prisma.ingredient.create({ data: { name: 'عجينة -- اختبار إنتاج معطّل', unit: 'g', kind: 'SEMI_FINISHED', lowStockThreshold: 0 } });
    await prisma.recipeLine.create({ data: { parentIngredientId: dough.id, ingredientId: rawFlour.id, quantity: 2 } });
    const item = await prisma.menuItem.create({ data: { name: 'صنف يستهلك عجينة (إنتاج معطّل)', category: 'رئيسي', price: 10 } });
    await prisma.recipeLine.create({ data: { menuItemId: item.id, ingredientId: dough.id, quantity: 5 } });

    const shiftRes = await request(app.getHttpServer()).post('/shifts').set(auth(adminToken)).send({ locationId: location.id, openingFloat: 100 });
    const orderRes = await request(app.getHttpServer())
      .post('/orders')
      .set(auth(adminToken))
      .send({ locationId: location.id, shiftId: shiftRes.body.id, channel: 'DINE_IN', lines: [{ menuItemId: item.id, quantity: 1 }] });
    expect(orderRes.status).toBe(201);

    const balance = await prisma.inventoryBalance.findFirst({ where: { locationId: location.id, ingredientId: dough.id } });
    expect(Number(balance!.quantity)).toBe(-5); // the sale still went negative --

    const listRes = await request(app.getHttpServer()).get(`/production-orders?locationId=${location.id}`).set(auth(adminToken));
    expect(listRes.body).toHaveLength(0); // -- but nothing was raised for it
  });

  it('lets a SEMI_FINISHED ingredient with its own recipe sell past zero when autoGenerateProductionOrders is on, even with allowNegativeStock off', async () => {
    // allowNegativeStock is deliberately left false here -- the point of
    // this test is that autoGenerateProductionOrders ALONE is enough to
    // keep the sale from being rejected, because the shortage is a fixable
    // production need (dough has its own recipe).
    const location = await prisma.location.create({ data: { name: 'فرع اختبار تغطية الإنتاج بدون سالب', type: 'BRANCH', autoGenerateProductionOrders: true } });
    const rawFlour = await prisma.ingredient.create({ data: { name: 'دقيق -- اختبار تغطية بدون سالب', unit: 'g', kind: 'RAW_MATERIAL', lowStockThreshold: 0 } });
    const dough = await prisma.ingredient.create({ data: { name: 'عجينة -- اختبار تغطية بدون سالب', unit: 'g', kind: 'SEMI_FINISHED', lowStockThreshold: 0 } });
    await prisma.recipeLine.create({ data: { parentIngredientId: dough.id, ingredientId: rawFlour.id, quantity: 2 } });
    const item = await prisma.menuItem.create({ data: { name: 'صنف يستهلك عجينة (تغطية بدون سالب)', category: 'رئيسي', price: 10 } });
    await prisma.recipeLine.create({ data: { menuItemId: item.id, ingredientId: dough.id, quantity: 5 } });

    const shiftRes = await request(app.getHttpServer()).post('/shifts').set(auth(adminToken)).send({ locationId: location.id, openingFloat: 100 });
    const orderRes = await request(app.getHttpServer())
      .post('/orders')
      .set(auth(adminToken))
      .send({ locationId: location.id, shiftId: shiftRes.body.id, channel: 'DINE_IN', lines: [{ menuItemId: item.id, quantity: 1 }] });
    expect(orderRes.status).toBe(201); // not rejected, despite allowNegativeStock being off

    const balance = await prisma.inventoryBalance.findFirst({ where: { locationId: location.id, ingredientId: dough.id } });
    expect(Number(balance!.quantity)).toBe(-5);

    const listRes = await request(app.getHttpServer()).get(`/production-orders?locationId=${location.id}`).set(auth(adminToken));
    expect(listRes.body).toHaveLength(1);
    expect(listRes.body[0].outputIngredientId).toBe(dough.id);
    expect(Number(listRes.body[0].outputQuantity)).toBe(5);
  });

  it('lets a RAW_MATERIAL sell past zero when autoGenerateProductionOrders is on, and raises an inputs-less restock alert for it', async () => {
    // A raw material has no "produce more of it" concept, so the order it
    // gets has no `inputs` -- it's a plain "go restock/buy N more" alert,
    // not a real BOM-backed production run.
    const location = await prisma.location.create({ data: { name: 'فرع اختبار خامة أولية بدون سالب', type: 'BRANCH', autoGenerateProductionOrders: true } });
    const rawIce = await prisma.ingredient.create({ data: { name: 'ثلج -- اختبار خامة بدون سالب', unit: 'g', kind: 'RAW_MATERIAL', lowStockThreshold: 0 } });
    const item = await prisma.menuItem.create({ data: { name: 'صنف يستهلك ثلج (خامة بدون سالب)', category: 'مشروبات', price: 5 } });
    await prisma.recipeLine.create({ data: { menuItemId: item.id, ingredientId: rawIce.id, quantity: 50 } });

    const shiftRes = await request(app.getHttpServer()).post('/shifts').set(auth(adminToken)).send({ locationId: location.id, openingFloat: 100 });
    const orderRes = await request(app.getHttpServer())
      .post('/orders')
      .set(auth(adminToken))
      .send({ locationId: location.id, shiftId: shiftRes.body.id, channel: 'DINE_IN', lines: [{ menuItemId: item.id, quantity: 1 }] });
    expect(orderRes.status).toBe(201); // not rejected, despite allowNegativeStock being off

    const balance = await prisma.inventoryBalance.findFirst({ where: { locationId: location.id, ingredientId: rawIce.id } });
    expect(Number(balance!.quantity)).toBe(-50);

    const listRes = await request(app.getHttpServer()).get(`/production-orders?locationId=${location.id}`).set(auth(adminToken));
    expect(listRes.body).toHaveLength(1);
    expect(listRes.body[0].outputIngredientId).toBe(rawIce.id);
    expect(Number(listRes.body[0].outputQuantity)).toBe(50);

    const detail = await request(app.getHttpServer()).get(`/production-orders/${listRes.body[0].id}`).set(auth(adminToken));
    expect(detail.body.inputs).toHaveLength(0);
  });

  it('lets a SEMI_FINISHED item with no recipe of its own sell past zero, and raises an inputs-less restock alert for it', async () => {
    // Same "no BOM to base real inputs on" situation as a RAW_MATERIAL --
    // the order still gets raised, just with an empty inputs list.
    const location = await prisma.location.create({ data: { name: 'فرع اختبار نصف مصنّع بدون وصفة', type: 'BRANCH', autoGenerateProductionOrders: true } });
    const sauce = await prisma.ingredient.create({ data: { name: 'صوص -- بدون وصفة', unit: 'g', kind: 'SEMI_FINISHED', lowStockThreshold: 0 } });
    const item = await prisma.menuItem.create({ data: { name: 'صنف يستهلك صوص بدون وصفة', category: 'رئيسي', price: 8 } });
    await prisma.recipeLine.create({ data: { menuItemId: item.id, ingredientId: sauce.id, quantity: 20 } });

    const shiftRes = await request(app.getHttpServer()).post('/shifts').set(auth(adminToken)).send({ locationId: location.id, openingFloat: 100 });
    const orderRes = await request(app.getHttpServer())
      .post('/orders')
      .set(auth(adminToken))
      .send({ locationId: location.id, shiftId: shiftRes.body.id, channel: 'DINE_IN', lines: [{ menuItemId: item.id, quantity: 1 }] });
    expect(orderRes.status).toBe(201);

    const listRes = await request(app.getHttpServer()).get(`/production-orders?locationId=${location.id}`).set(auth(adminToken));
    expect(listRes.body).toHaveLength(1);
    expect(listRes.body[0].outputIngredientId).toBe(sauce.id);
    expect(Number(listRes.body[0].outputQuantity)).toBe(20);

    const detail = await request(app.getHttpServer()).get(`/production-orders/${listRes.body[0].id}`).set(auth(adminToken));
    expect(detail.body.inputs).toHaveLength(0);
  });

  it('rolls shortages from multiple invoices in the same shift into one PLANNED production order, without allowNegativeStock', async () => {
    const location = await prisma.location.create({ data: { name: 'فرع اختبار تجميع عدة فواتير', type: 'BRANCH', autoGenerateProductionOrders: true } });
    const rawSugar = await prisma.ingredient.create({ data: { name: 'سكر -- اختبار تجميع فواتير', unit: 'g', kind: 'RAW_MATERIAL', lowStockThreshold: 0 } });
    const syrup = await prisma.ingredient.create({ data: { name: 'شراب -- اختبار تجميع فواتير', unit: 'g', kind: 'SEMI_FINISHED', lowStockThreshold: 0 } });
    await prisma.recipeLine.create({ data: { parentIngredientId: syrup.id, ingredientId: rawSugar.id, quantity: 1 } });
    const item = await prisma.menuItem.create({ data: { name: 'صنف يستهلك شراب (تجميع فواتير)', category: 'حلويات', price: 8 } });
    await prisma.recipeLine.create({ data: { menuItemId: item.id, ingredientId: syrup.id, quantity: 4 } });

    const shiftRes = await request(app.getHttpServer()).post('/shifts').set(auth(adminToken)).send({ locationId: location.id, openingFloat: 100 });
    const shiftId = shiftRes.body.id;

    const order1 = await request(app.getHttpServer())
      .post('/orders')
      .set(auth(adminToken))
      .send({ locationId: location.id, shiftId, channel: 'DINE_IN', lines: [{ menuItemId: item.id, quantity: 1 }] });
    expect(order1.status).toBe(201);
    const order2 = await request(app.getHttpServer())
      .post('/orders')
      .set(auth(adminToken))
      .send({ locationId: location.id, shiftId, channel: 'DINE_IN', lines: [{ menuItemId: item.id, quantity: 2 }] });
    expect(order2.status).toBe(201);

    const listRes = await request(app.getHttpServer()).get(`/production-orders?locationId=${location.id}`).set(auth(adminToken));
    expect(listRes.body).toHaveLength(1); // one shared PLANNED order, not two
    expect(Number(listRes.body[0].outputQuantity)).toBe(12); // 4 (order 1) + 8 (order 2, qty 2)
    expect(listRes.body[0].shiftId).toBe(shiftId);
  });
});
